# Generated by Django 4.2.30 on 2026-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_updated_time_alter_contact_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
