# Generated by Django 4.2.30 on 2026-04-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Number',
            field=models.CharField(max_length=15),
        ),
    ]
