# Generated by Django 4.2.30 on 2026-05-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_category_alter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Token',
            field=models.CharField(max_length=500),
        ),
    ]
